config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Sidekiq::Web => '/queue'

  devise_for :users

  root 'pages#index'

  get '/privacy-policy' => 'pages#privacy'
  get '/terms' => 'pages#terms'

  get '/ping', to: proc { [200, {}, ['pong']] }

  get '/account' => 'accounts#index', as: 'account'

  get '/payment' => 'accounts#payment', as: 'payment'
  post '/payment/process' => 'accounts#process_payment', as: 'process_payment'
  get '/payment/upgrade' => 'accounts#upgrade', as: 'upgrade'
  patch '/payment/upgrade' => 'accounts#process_upgrade'

  get '/domains' => 'domains#index', as: 'domains'
  post '/domains' => 'domains#create', as: 'domain'
  get '/domains/new' => 'domains#new', as: 'new_domain'
  get '/domains/:domain' => 'domains#edit', as: 'edit_domain', constraints: { domain: /[^\/]+/ }
  delete '/domains/:domain' => 'domains#delete', as: 'delete_domain', constraints: { domain: /[^\/]+/ }
  post '/domains/:domain/disable' => 'domains#disable', as: 'disable_domain', constraints: { domain: /[^\/]+/ }
  post '/domains/:domain/enable' => 'domains#enable', as: 'enable_domain', constraints: { domain: /[^\/]+/ }

  get '/domains/:domain/records/new/a' => 'records#a', as: 'new_a_record', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/new/aaaa' => 'records#aaaa', as: 'new_aaaa_record', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/new/cname' => 'records#cname', as: 'new_cname_record', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/new/forwarder' => 'records#forwarder', as: 'new_forwarder_record', constraints: { domain: /[^\/]+/ }
  post '/domains/:domain/records/new/forwarder' => 'records#create_forwarder', as: 'delete_forwarder_record', constraints: { domain: /[^\/]+/ }
  delete '/domains/:domain/records/forwarder/:id' => 'records#delete_forwarder', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/new/mx' => 'records#mx', as: 'new_mx_record', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/new/spf' => 'records#spf', as: 'new_spf_record', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/new/srv' => 'records#srv', as: 'new_srv_record', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/new/txt' => 'records#txt', as: 'new_txt_record', constraints: { domain: /[^\/]+/ }
  post '/domains/:domain/records' => 'records#create', as: 'record', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/:id' => 'records#edit', as: 'edit_record', constraints: { domain: /[^\/]+/ }
  post '/domains/:domain/records/:id' => 'records#update', constraints: { domain: /[^\/]+/ }
  delete '/domains/:domain/records/:id' => 'records#delete', as: 'delete_record', constraints: { domain: /[^\/]+/ }

end

app/models/record.rb
class Record < ActiveRecord::Base

  def self.attributes_protected_by_default
    []
  end

  belongs_to :domain, counter_cache: true

  validates_presence_of :domain_id, :name
  validates_numericality_of :ttl,
    :greater_than_or_equal_to => 0,
    :only_integer => true

  class_attribute :batch_soa_updates

  # This is needed here for generic form support, actual functionality
  # implemented in #SOA
  attr_accessor :primary_ns, :contact, :refresh, :retry, :expire, :minimum

  before_validation :inherit_attributes_from_domain
  before_save :update_change_date
  after_save  :update_soa_serial
  after_destroy  :update_soa_serial

  # Known record types

  class_attribute :record_types
  self.record_types = ['A', 'AAAA', 'CNAME', 'LOC', 'MX', 'NS', 'PTR', 'SOA', 'SPF', 'SRV', 'SSHFP', 'TXT']

  class << self

    # Restrict the SOA serial number updates to just one during the execution
    # of the block. Useful for batch updates to a zone
    def batch
      raise ArgumentError, "Block expected" unless block_given?

      self.batch_soa_updates = []
      yield
      self.batch_soa_updates = nil
    end

  end

  def shortname
    self[:name].gsub( /\.?#{self.domain.name}$/, '' )
  end

  def shortname=( value )
    self[:name] = value
  end

  # Nicer representation of the domain as XML
  def to_xml_with_cleanup(options = {}, &block)
    to_xml_without_cleanup(options, &block)
  end
  alias_method_chain :to_xml, :cleanup

  # Pull in the name & TTL from the domain if missing
  def inherit_attributes_from_domain #:nodoc:
    unless self.domain_id.nil?
      append_domain_name!
      self.ttl ||= self.domain.ttl
    end
  end

  # Update the change date for automatic serial number generation
  def update_change_date
    self.change_date = Time.now.to_i
  end

  def update_soa_serial #:nodoc:
    unless self.type == 'SOA'
      self.domain.soa_record.update_serial! if self.domain && self.domain.soa_record
    end
  end

  # By default records don't support priorities. Those who do can overwrite
  # this in their own classes.
  def supports_prio?
    false
  end

  def allowed?
    return true if ['A', 'AAAA', 'CNAME', 'LOC', 'MX', 'PTR', 'SPF', 'SRV', 'SSHFP', 'TXT'].include?(type)
  end

  private

  # Append the domain name to the +name+ field if missing
  def append_domain_name!
    self[:name] = self.domain.name if self[:name].blank?

    self[:name] << ".#{self.domain.name}" unless self[:name].index( self.domain.name )
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController

  before_filter :check_user

  def a
    @domain = current_user.domains.where(name: params[:domain]).first
    @record = @domain.a_records.new
    render :new
  end

  def aaaa
    @domain = current_user.domains.where(name: params[:domain]).first
    @record = @domain.aaaa_records.new
    render :new
  end

  def cname
    @domain = current_user.domains.where(name: params[:domain]).first
    @record = @domain.cname_records.new
    render :new
  end

  def forwarder
    @domain = current_user.domains.where(name: params[:domain]).first
    @forwarder = @domain.forwarders.new
  end

  def create_forwarder
    @domain = current_user.domains.where(name: params[:domain]).first
    @forwarder = @domain.forwarders.new(forwarder_params)
    if @forwarder.save
      redirect_to "/domains/#{@domain.name}"
    else
      render :forwarder
    end
  end

  def delete_forwarder
    @domain = current_user.domains.where(name: params[:domain]).first
    @forwarder = @domain.forwarders.find(params[:id])
    if @forwarder.destroy
      redirect_to "/domains/#{@domain.name}"
    else
      redirect_to "/domains/#{@domain.name}"
    end
  end

  def mx
    @domain = current_user.domains.where(name: params[:domain]).first
    @record = @domain.mx_records.new
    render :new
  end

  def spf
    @domain = current_user.domains.where(name: params[:domain]).first
    @record = @domain.spf_records.new
    render :new
  end

  def srv
    @domain = current_user.domains.where(name: params[:domain]).first
    @record = @domain.srv_records.new
    render :new
  end

  def txt
    @domain = current_user.domains.where(name: params[:domain]).first
    @record = @domain.txt_records.new
    render :new
  end

  def create
    @domain = current_user.domains.where(name: params[:domain]).first
    @record = @domain.records.new(record_params)
    if @record.save
      redirect_to "/domains/#{@domain.name}"
    else
      render :new
    end
  end

  def edit
    @domain = current_user.domains.where(name: params[:domain]).first
    @record = @domain.records.find(params[:id]) if @domain
    if @domain.blank? || @record.blank? || !@record.allowed?
      flash[:error] = "You are not allowed to edit that record."
      redirect_to "/"
      return
    end
  end

  def update
    @domain = current_user.domains.where(name: params[:domain]).first
    @record = @domain.records.find(params[:id]) if @domain
    if @domain.blank? || @record.blank? || !@record.allowed?
      redirect_to "/"
      return
    end
    if @record.update_attributes(record_params)
      redirect_to "/domains/#{@domain.name}"
    else
      render :edit
    end
  end

  def delete
    @domain = current_user.domains.where(name: params[:domain]).first
    @record = @domain.records.find(params[:id])
    if @record && @record.destroy
      redirect_to "/domains/#{@domain.name}"
    else
      redirect_to "/domains/#{@domain.name}"
    end
  end

  private

    def check_user
      unless current_user
        redirect_to root_path
        return
      end
    end

    def record_params
      params.require(:record).permit(:id, :name, :type, :content, :ttl, :prio)
    end

    def forwarder_params
      params.require(:forwarder).permit(:id, :name, :content)
    end

end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/edit.html.haml
%h6
  Update #{@record.type} Record -
  = @domain.name

%hr

.row
  .col-md-6
    = form_for(:record, url: "/domains/#{@domain.name}/records/#{@record.id}", html: {class: "form-horizontal"}) do |f|
      = f.hidden_field :type, value: @record.type

      - if @record.errors.any?
        .alert.alert-danger
          %h4
            Sorry, there was an error.
          %ul
            - @record.errors.full_messages.uniq.each do |msg|
              %li
                = msg

      .form-group
        = f.label :name, "Domain Name", class: " col-md-3 control-label"
        .col-md-9
          = f.text_field :name, autofocus: true, class: "form-control", placeholder: @domain.name

      - if @record.type == "MX"
        .form-group
          = f.label :prio, "Priority", class: " col-md-3 control-label"
          .col-md-9
            = f.number_field :prio, value: 1, class: "form-control", min: 1

      .form-group
        = f.label :content, "Value", class: " col-md-3 control-label"
        .col-md-9
          = f.text_field :content, autofocus: true, class: "form-control"

      .form-group
        = f.label :ttl, "TTL", class: " col-md-3 control-label"
        .col-md-9
          = f.select :ttl, TTL, {include_blank: false, selected: 3600}, {class: 'form-control'}

      .form-group
        .col-md-offset-3.col-md-9
          %button.btn.btn-primary{:type => "submit"}
            Update
          %a{href: "/domains/#{@domain.name}", class: "btn btn-default"}
            Cancel

app/views/records/forwarder.html.haml
%h6
  New Forwarder Record -
  = @domain.name

%hr

.row
  .col-md-6
    = form_for(@forwarder, url: new_forwarder_record_path(@domain.name), html: {class: "form-horizontal"}) do |f|

      - if @forwarder.errors.any?
        #error_explanation
          %h2
            = pluralize(@forwarder.errors.count, "error")
            prohibited this article from being saved:
          %ul
            - @forwarder.errors.full_messages.each do |msg|
              %li
                = msg

      .form-group
        = f.label :name, "Domain Name", class: " col-md-3 control-label"
        .col-md-9
          = f.text_field :name, autofocus: true, class: "form-control", placeholder: @domain.name

      .form-group
        = f.label :content, "Forward to", class: " col-md-3 control-label"
        .col-md-9
          = f.text_field :content, autofocus: true, class: "form-control"

      .form-group
        .col-md-offset-3.col-md-9
          %button.btn.btn-primary{:type => "submit"}
            Create
          %a{href: "/domains/#{@domain.name}", class: "btn btn-default"}
            Cancel

app/views/records/new.html.haml
%h6
  New #{@record.type} Record -
  = @domain.name

%hr

.row
  .col-md-6
    = form_for(:record, url: record_path, html: {class: "form-horizontal"}) do |f|
      = f.hidden_field :type, value: @record.type

      - if @record.errors.any?
        .alert.alert-danger
          %h4
            Sorry, there was an error.
          %ul
            - @record.errors.full_messages.uniq.each do |msg|
              %li
                = msg

      .form-group
        = f.label :name, "Domain Name", class: " col-md-3 control-label"
        .col-md-9
          = f.text_field :name, autofocus: true, class: "form-control", placeholder: @domain.name

      - if @record.type == "MX"
        .form-group
          = f.label :prio, "Priority", class: " col-md-3 control-label"
          .col-md-9
            = f.number_field :prio, value: 1, class: "form-control", min: 1

      .form-group
        = f.label :content, "Value", class: " col-md-3 control-label"
        .col-md-9
          = f.text_field :content, autofocus: true, class: "form-control"

      .form-group
        = f.label :ttl, "TTL", class: " col-md-3 control-label"
        .col-md-9
          = f.select :ttl, TTL, {include_blank: false, selected: 3600}, {class: 'form-control'}

      .form-group
        .col-md-offset-3.col-md-9
          %button.btn.btn-primary{:type => "submit"}
            Create
          %a{href: "/domains/#{@domain.name}", class: "btn btn-default"}
            Cancel