config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Sidekiq::Web => '/queue'

  devise_for :users

  root 'pages#index'

  get '/privacy-policy' => 'pages#privacy'
  get '/terms' => 'pages#terms'

  get '/ping', to: proc { [200, {}, ['pong']] }

  get '/account' => 'accounts#index', as: 'account'

  get '/payment' => 'accounts#payment', as: 'payment'
  post '/payment/process' => 'accounts#process_payment', as: 'process_payment'
  get '/payment/upgrade' => 'accounts#upgrade', as: 'upgrade'
  patch '/payment/upgrade' => 'accounts#process_upgrade'

  get '/domains' => 'domains#index', as: 'domains'
  post '/domains' => 'domains#create', as: 'domain'
  get '/domains/new' => 'domains#new', as: 'new_domain'
  get '/domains/:domain' => 'domains#edit', as: 'edit_domain', constraints: { domain: /[^\/]+/ }
  delete '/domains/:domain' => 'domains#delete', as: 'delete_domain', constraints: { domain: /[^\/]+/ }
  post '/domains/:domain/disable' => 'domains#disable', as: 'disable_domain', constraints: { domain: /[^\/]+/ }
  post '/domains/:domain/enable' => 'domains#enable', as: 'enable_domain', constraints: { domain: /[^\/]+/ }

  get '/domains/:domain/records/new/a' => 'records#a', as: 'new_a_record', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/new/aaaa' => 'records#aaaa', as: 'new_aaaa_record', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/new/cname' => 'records#cname', as: 'new_cname_record', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/new/forwarder' => 'records#forwarder', as: 'new_forwarder_record', constraints: { domain: /[^\/]+/ }
  post '/domains/:domain/records/new/forwarder' => 'records#create_forwarder', as: 'delete_forwarder_record', constraints: { domain: /[^\/]+/ }
  delete '/domains/:domain/records/forwarder/:id' => 'records#delete_forwarder', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/new/mx' => 'records#mx', as: 'new_mx_record', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/new/spf' => 'records#spf', as: 'new_spf_record', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/new/srv' => 'records#srv', as: 'new_srv_record', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/new/txt' => 'records#txt', as: 'new_txt_record', constraints: { domain: /[^\/]+/ }
  post '/domains/:domain/records' => 'records#create', as: 'record', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/:id' => 'records#edit', as: 'edit_record', constraints: { domain: /[^\/]+/ }
  post '/domains/:domain/records/:id' => 'records#update', constraints: { domain: /[^\/]+/ }
  delete '/domains/:domain/records/:id' => 'records#delete', as: 'delete_record', constraints: { domain: /[^\/]+/ }

end

app/models/domain.rb
class Domain < ActiveRecord::Base

  self.inheritance_column = nil

  attr_accessor :serial

  validates_presence_of :name
  validates_uniqueness_of :name

  belongs_to :user

  has_many :records, dependent: :destroy
  has_many :forwarders, dependent: :destroy

  has_one  :soa_record, class_name: 'SOA'
  has_many :ns_records, class_name: 'NS'
  has_many :mx_records, class_name: 'MX'
  has_many :a_records, class_name: 'A'
  has_many :txt_records, class_name: 'TXT'
  has_many :cname_records, class_name: 'CNAME'
  has_one  :loc_record, class_name: 'LOC'
  has_many :aaaa_records, class_name: 'AAAA'
  has_many :spf_records, class_name: 'SPF'
  has_many :srv_records, class_name: 'SRV'
  has_many :sshfp_records, class_name: 'SSHFP'
  has_many :ptr_records, class_name: 'PTR'

  has_one :whois_record, dependent: :destroy

  validates_presence_of :name
  validates_uniqueness_of :name

  after_create :create_soa_record
  after_create :setup_ns_records
  after_create :check_whois
  after_destroy :process_payment

  SOA_FIELDS = [ :primary_ns, :contact, :refresh, :retry, :expire, :minimum ]
  SOA_FIELDS.each do |f|
    attr_accessor f
    validates_presence_of f, :on => :create
  end

  def self.enabled_count(user_id)
    enabled_domains = []
    user = User.find(user_id)
    user.domains.each do |domain|
      enabled_domains.push(domain) if domain.enabled?
    end
    enabled_domains.count
  end

  def enabled?
    !soa_record.disabled
  end

  def disable
    soa_record.disabled = true
    soa_record.save
    process_payment
  end

  def enable
    soa_record.disabled = false
    soa_record.save
    process_payment
  end

  def create_soa_record
    soa = SOA.new( :domain => self )
    SOA_FIELDS.each do |f|
      soa.send( "#{f}=", send( f ) )
    end
    soa.serial = serial unless serial.nil?
    soa.disabled = true
    if soa.save
    else
      puts "==========\n#{soa.errors.messages if soa.errors}\n==========="
    end
  end

  def setup_ns_records
    domain = self
    domain.records.create(name: domain.name, type: "NS", content: "ns1.dnslabs.co", ttl: 7200)
    domain.records.create(name: domain.name, type: "NS", content: "ns2.dnslabs.co", ttl: 7200)
    domain.records.create(name: domain.name, type: "NS", content: "ns3.dnslabs.co", ttl: 7200)
    domain.records.create(name: domain.name, type: "NS", content: "ns4.dnslabs.co", ttl: 7200)
  end

  def check_whois
    domain = self
    record = Whois.whois(domain.name)
    whois_record = domain.whois_record || domain.build_whois_record
    whois_record.status = record.status.class == Array ? record.status.last.to_s : record.status.to_s if record.property_any_supported?(:status)
    whois_record.available = record.available? if record.property_any_supported?(:available?)
    whois_record.registered = record.registered? if record.property_any_supported?(:registered?)
    whois_record.created_on = record.created_on if record.property_any_supported?(:created_on)
    whois_record.updated_on = record.updated_on if record.property_any_supported?(:updated_on)
    whois_record.expires_on = record.expires_on if record.property_any_supported?(:expires_on)
    whois_record.check_on = Time.now
    whois_record.save

    if record.property_any_supported?(:nameservers)
      whois_record.whois_nameservers.destroy_all
      record.nameservers.each do |nameserver|
        whois_record.whois_nameservers.create(name: nameserver.name)
      end
    end

  end

  def process_payment
    ProcessPaymentWorker.perform_async(self.user.id)
  end

end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController

  before_filter :check_user

  def index
    @domains = current_user.domains.order("name ASC")
  end

  def new
    @domain = Domain.new
  end

  def create
    @domain = current_user.domains.new(domain_params)

    @domain.type = "NATIVE"
    @domain.primary_ns = PRIMARY_NS
    @domain.contact = CONTACT
    @domain.refresh = REFRESH
    @domain.retry = RETRY
    @domain.expire = EXPIRE
    @domain.minimum = MINIMUM

    if @domain.save
      redirect_to "/domains/"
    else
      render :new
    end
  end

  def edit
    @domain = current_user.domains.where(name: params[:domain]).first
    @records = @domain.records.order("type ASC, name ASC") if @domain
    @forwarders = @domain.forwarders.order("name ASC") if @domain
  end

  def delete
    @domain = current_user.domains.where(name: params[:domain]).first
    if @domain && @domain.destroy
      redirect_to domains_path
    else
      redirect_to domains_path
    end
  end

  def disable
    @domain = current_user.domains.where(name: params[:domain]).first
    @domain.disable
    redirect_to domains_path
  end

  def enable
    @domain = current_user.domains.where(name: params[:domain]).first
    @domain.enable
    redirect_to domains_path
  end

  private

    def check_user
      unless current_user
        redirect_to root_path
        return
      end
    end

    def domain_params
      params.require(:domain).permit(:id, :name)
    end

end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/domains/edit.html.haml
%h6
  Domains -
  = @domain.name

%hr

%p
  .dropdown
    %button.btn.btn-primary{"data-toggle" => "dropdown", :type => "button"}
      New Record
      %span.caret
    %ul.dropdown-menu
      %li
        %a{:href => new_a_record_path(@domain.name)}
          A Record
      %li
        %a{:href => new_aaaa_record_path(@domain.name)}
          AAAA Record
      %li
        %a{:href => new_cname_record_path(@domain.name)}
          CNAME Record
      %li
        %a{:href => new_forwarder_record_path(@domain.name)}
          FORWARD Record
      %li
        %a{:href => new_mx_record_path(@domain.name)}
          MX Record
      %li
        %a{:href => new_spf_record_path(@domain.name)}
          SPF Record
      %li
        %a{:href => new_srv_record_path(@domain.name)}
          SRV Record
      %li
        %a{:href => new_txt_record_path(@domain.name)}
          TXT Record

- if !@records.blank?
  .table-responsive
    %table.table.table-bordered.table-hover.records
      %thead
        %tr
          %th.record
            Record
          %th.type
            Type
          %th.ttl
            TTL
          %th.content
            Value
          %th.controls
      %tbody
        - @forwarders.each do |forward|
          %tr
            %td
              = forward.name
            %td
              FORWARDER
            %td

            %td
              = forward.content
            %td
              %button{class: "btn btn-primary", disabled: true}
                edit
              = link_to "delete", "/domains/#{@domain.name}/records/forwarder/#{forward.id}", method: :delete, class: "btn btn-danger", :data => {:confirm => 'Are you sure?'}

        - @records.each do |record|
          %tr.record
            %td
              = record.name
            %td
              = record.type
            %td
              - if record.ttl.blank?
                3600
              - else
                = record.ttl
            %td.content
              - if record.type == "MX"
                #{record.prio} #{record.content}
              - else
                = record.content
            %td
              - if record.type == "SOA" || record.type == "NS" || !record.forwarder_id.nil?
                %button{class: "btn btn-primary", disabled: true}
                  edit
                %button{class: "btn btn-danger", disabled: true}
                  delete
              - else
                = link_to "edit", "/domains/#{@domain.name}/records/#{record.id}", class: "btn btn-primary"
                = link_to "delete", "/domains/#{@domain.name}/records/#{record.id}", method: :delete, class: "btn btn-danger", :data => {:confirm => 'Are you sure?'}

app/views/domains/index.html.haml
%h6
  Domains

%hr

%p
  = link_to "New Domain", new_domain_path, class: "btn btn-primary"

- if Domain.enabled_count(current_user.id) < current_user.domains.count
  .alert.alert-warning
    %button.close.fui-cross{"data-dismiss" => "alert", :type => "button"}
    Domains must be enabled before they will resolve. You are only charged for enabled domains.

- if !@domains.blank?
  .table-responsive
    %table.table.table-bordered.table-hover.domains
      %thead
        %tr
          %th
            Domain
          %th
            Records
          %th
            Expires In
          %th.controls
      %tbody
        - @domains.each do |domain|
          %tr.domain
            %td
              = domain.name
            %td
              = domain.records.count
              Records
            %td
              - if domain.whois_record && domain.whois_record.expires_on
                - if domain.whois_record.expires_on > Time.now
                  = distance_of_time_in_words(Time.now, domain.whois_record.expires_on)
                - else
                  = distance_of_time_in_words(domain.whois_record.expires_on, Time.now)
                  ago
              - else
                Unknown
            %td
              = link_to "edit", "/domains/#{domain.name}", class: "btn btn-primary"
              = link_to domain.enabled? ? "disable" : "enable", "/domains/#{domain.name}/#{domain.enabled? ? 'disable' : 'enable'}", class: "btn #{domain.enabled? ? 'btn-warning' : 'btn-primary'}", method: :post, :data => {:confirm => 'Are you sure?'}
              = link_to "delete", "/domains/#{domain.name}", method: :delete, class: "btn btn-danger", :data => {:confirm => 'Are you sure?'}

app/views/domains/new.html.haml
%h6
  Domains - New Domain

%hr

.row
  .col-md-6
    = form_for(@domain, url: domain_path, html: {class: "form-horizontal"}) do |f|
      - if @domain.errors.any?
        .alert.alert-danger
          %h4
            Sorry, there was an error.
          %ul
            - @domain.errors.full_messages.uniq.each do |msg|
              %li
                = msg

      .form-group
        = f.label :name, "Domain Name", class: " col-md-3 control-label"
        .col-md-9
          = f.text_field :name, autofocus: true, class: "form-control", placeholder: "example.com"

      .form-group
        .col-md-offset-3.col-md-9
          %button.btn.btn-primary{:type => "submit"}
            Create
          %a{href: "/domains", class: "btn btn-default"}
            Cancel

  .col-md-6
    %p
      To use DNS Labs you will need to update your name servers to the following records -

    %p
      %ul
        %li
          ns1.dnslabs.co (104.197.71.175)
        %li
          ns2.dnslabs.co (104.196.15.154)
        %li
          ns3.dnslabs.co (104.155.196.107)
        %li
          ns4.dnslabs.co (104.155.40.204)