config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Sidekiq::Web => '/queue'

  devise_for :users

  root 'pages#index'

  get '/privacy-policy' => 'pages#privacy'
  get '/terms' => 'pages#terms'

  get '/ping', to: proc { [200, {}, ['pong']] }

  get '/account' => 'accounts#index', as: 'account'

  get '/payment' => 'accounts#payment', as: 'payment'
  post '/payment/process' => 'accounts#process_payment', as: 'process_payment'
  get '/payment/upgrade' => 'accounts#upgrade', as: 'upgrade'
  patch '/payment/upgrade' => 'accounts#process_upgrade'

  get '/domains' => 'domains#index', as: 'domains'
  post '/domains' => 'domains#create', as: 'domain'
  get '/domains/new' => 'domains#new', as: 'new_domain'
  get '/domains/:domain' => 'domains#edit', as: 'edit_domain', constraints: { domain: /[^\/]+/ }
  delete '/domains/:domain' => 'domains#delete', as: 'delete_domain', constraints: { domain: /[^\/]+/ }
  post '/domains/:domain/disable' => 'domains#disable', as: 'disable_domain', constraints: { domain: /[^\/]+/ }
  post '/domains/:domain/enable' => 'domains#enable', as: 'enable_domain', constraints: { domain: /[^\/]+/ }

  get '/domains/:domain/records/new/a' => 'records#a', as: 'new_a_record', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/new/aaaa' => 'records#aaaa', as: 'new_aaaa_record', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/new/cname' => 'records#cname', as: 'new_cname_record', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/new/forwarder' => 'records#forwarder', as: 'new_forwarder_record', constraints: { domain: /[^\/]+/ }
  post '/domains/:domain/records/new/forwarder' => 'records#create_forwarder', as: 'delete_forwarder_record', constraints: { domain: /[^\/]+/ }
  delete '/domains/:domain/records/forwarder/:id' => 'records#delete_forwarder', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/new/mx' => 'records#mx', as: 'new_mx_record', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/new/spf' => 'records#spf', as: 'new_spf_record', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/new/srv' => 'records#srv', as: 'new_srv_record', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/new/txt' => 'records#txt', as: 'new_txt_record', constraints: { domain: /[^\/]+/ }
  post '/domains/:domain/records' => 'records#create', as: 'record', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/:id' => 'records#edit', as: 'edit_record', constraints: { domain: /[^\/]+/ }
  post '/domains/:domain/records/:id' => 'records#update', constraints: { domain: /[^\/]+/ }
  delete '/domains/:domain/records/:id' => 'records#delete', as: 'delete_record', constraints: { domain: /[^\/]+/ }

end

app/views/layouts/_layout.html.haml
!!!
%html{lang: "en"}
  %head
    %title
      DNS Service | Simple DNS hosting with a 30 day free trial | DNS Labs
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}
    %meta{:content => "Cheap DNS Service with a simple to use web interface, and a powerful REST API to make automation easy.", :name => "description"}
    %meta{:content => "a067335251aa2099d94a", :name => "wot-verification"}
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    %script{:src => "https://js.stripe.com/v2/", :type => "text/javascript"}
    %script{:src => "https://use.typekit.net/hdq2not.js"}
    :javascript
      try{Typekit.load({ async: true });}catch(e){}

    /[if lt IE 9]
      %script{:src => "/assets/lib/html5shiv.js"}
      %script{:src => "/assets/lib/respond.min.js"}

    :javascript
      !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
      n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
      n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
      t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
      document,'script','//connect.facebook.net/en_US/fbevents.js');

      fbq('init', '556501511179156');
      fbq('track', "PageView");

    = csrf_meta_tags

  %body#page
    .navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
          %a.navbar-brand{:href => "/"}
            DNS Labs
        .navbar-collapse.collapse
          %ul.nav.navbar-nav.navbar-right
            - if current_user
              %li{class: "#{params[:controller] == 'domains' || params[:controller] == 'records' ? 'active' : ''}"}
                = link_to "Domains", domains_path
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  Account
                  %b.caret
                %ul.dropdown-menu
                  %li
                    %a{:href => "#"}
                      Update Details
                  %li
                    %a{:href => "#"}
                      Close account
              %li
                = link_to "Log out", destroy_user_session_path, method: :delete
            - else
              %li
                = link_to "Log in", user_session_path
              %li
                = link_to "Register", new_user_registration_path, class: "take-control"


    .container
      - if current_user
        .alert.alert-success
          During our testing phase all new accounts will recieve 50% off their monthly invoice, for the life of their account.
          %br
          This discount will be manually applied, please email
          %a{href: "mailto:support@dnslabs.co"}
            support@dnslabs.co
          if you have any questions.

      - flash.each do |name, msg|
        - unless name == 'timedout'
          .row
            .col-md-8.col-md-offset-2
              %div{class: "alert alert-#{name == 'error' ? 'danger' : name == 'notice' ? 'success' : 'warning'} #{name}"}
                %button.close.fui-cross{"data-dismiss" => "alert", :type => "button"}
                = msg

      .row
        .col-sm-12.col-md-12.col-lg-12
          = yield

    %footer.footer
      .bottom-menu.bottom-menu-inverse
        .container
          .row
            .col-md-2.col-sm-2
              %a.bottom-menu-brand{:href => "/"}
                DNS Labs
            .col-md-8.col-sm-8
              %ul.bottom-menu-list
                %li
                  %a{:href => "/privacy-policy"}
                    Privacy
                %li
                  %a{:href => "/terms"}
                    Terms
                %li
                  %a{:href => "http://support.dnslabs.co", target: "_blank"}
                    Support
            .col-md-2.col-sm-2
              %ul.bottom-menu-iconic-list
                %li
                  %a.fui-twitter{:href => "https://twitter.com/dnslabs", target: "_blank"}

    %script{:src => "//platform.twitter.com/oct.js", :type => "text/javascript"}
    :javascript
      twttr.conversion.trackPid('nu4bs', { tw_sale_amount: 0, tw_order_quantity: 0 });

    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-72228328-1', 'auto');
      ga('send', 'pageview');

    %img{:alt => "", :height => "1", :src => "https://analytics.twitter.com/i/adsct?txn_id=nu4bs&p_id=Twitter&tw_sale_amount=0&tw_order_quantity=0", :style => "display:none;", :width => "1"}
    %img{:alt => "", :height => "1", :src => "//t.co/i/adsct?txn_id=nu4bs&p_id=Twitter&tw_sale_amount=0&tw_order_quantity=0", :style => "display:none;", :width => "1"}

    %img{:height => "1", :src => "https://www.facebook.com/tr?id=556501511179156&ev=PageView&noscript=1", :style => "display:none", :width => "1"}

app/views/layouts/application.html.haml
= render partial: "layouts/layout"

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %title
      DNS Labs
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    %script{:src => "https://js.stripe.com/v2/", :type => "text/javascript"}
    %script{:src => "https://use.typekit.net/hdq2not.js"}
    :javascript
      try{Typekit.load({ async: true });}catch(e){}

    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-69155745-1', 'auto');
      ga('send', 'pageview');

    = csrf_meta_tags
  %body
    .container
      = yield

app/views/layouts/pages.html.haml
= render partial: "layouts/layout"