config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Sidekiq::Web => '/queue'

  devise_for :users

  root 'pages#index'

  get '/privacy-policy' => 'pages#privacy'
  get '/terms' => 'pages#terms'

  get '/ping', to: proc { [200, {}, ['pong']] }

  get '/account' => 'accounts#index', as: 'account'

  get '/payment' => 'accounts#payment', as: 'payment'
  post '/payment/process' => 'accounts#process_payment', as: 'process_payment'
  get '/payment/upgrade' => 'accounts#upgrade', as: 'upgrade'
  patch '/payment/upgrade' => 'accounts#process_upgrade'

  get '/domains' => 'domains#index', as: 'domains'
  post '/domains' => 'domains#create', as: 'domain'
  get '/domains/new' => 'domains#new', as: 'new_domain'
  get '/domains/:domain' => 'domains#edit', as: 'edit_domain', constraints: { domain: /[^\/]+/ }
  delete '/domains/:domain' => 'domains#delete', as: 'delete_domain', constraints: { domain: /[^\/]+/ }
  post '/domains/:domain/disable' => 'domains#disable', as: 'disable_domain', constraints: { domain: /[^\/]+/ }
  post '/domains/:domain/enable' => 'domains#enable', as: 'enable_domain', constraints: { domain: /[^\/]+/ }

  get '/domains/:domain/records/new/a' => 'records#a', as: 'new_a_record', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/new/aaaa' => 'records#aaaa', as: 'new_aaaa_record', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/new/cname' => 'records#cname', as: 'new_cname_record', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/new/forwarder' => 'records#forwarder', as: 'new_forwarder_record', constraints: { domain: /[^\/]+/ }
  post '/domains/:domain/records/new/forwarder' => 'records#create_forwarder', as: 'delete_forwarder_record', constraints: { domain: /[^\/]+/ }
  delete '/domains/:domain/records/forwarder/:id' => 'records#delete_forwarder', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/new/mx' => 'records#mx', as: 'new_mx_record', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/new/spf' => 'records#spf', as: 'new_spf_record', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/new/srv' => 'records#srv', as: 'new_srv_record', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/new/txt' => 'records#txt', as: 'new_txt_record', constraints: { domain: /[^\/]+/ }
  post '/domains/:domain/records' => 'records#create', as: 'record', constraints: { domain: /[^\/]+/ }
  get '/domains/:domain/records/:id' => 'records#edit', as: 'edit_record', constraints: { domain: /[^\/]+/ }
  post '/domains/:domain/records/:id' => 'records#update', constraints: { domain: /[^\/]+/ }
  delete '/domains/:domain/records/:id' => 'records#delete', as: 'delete_record', constraints: { domain: /[^\/]+/ }

end

app/models/account.rb
class Account < ActiveRecord::Base

  belongs_to :user

  def create_customer(token=nil)
    begin
      account = self
      current_user = account.user

      Stripe.api_key = SECRET_KEY

      customer = Stripe::Customer.create(email: current_user.email, source: token)

      account.customer_id = customer.id
      account.save
      return true
    rescue
      return false
    end
  end

  def create_subscription(quantity=1)
    begin
      account = self
      current_user = account.user

      Stripe.api_key = SECRET_KEY

      customer = Stripe::Customer.retrieve(account.customer_id)

      subscription = customer.subscriptions.create(:plan => "domain", :quantity => quantity)

      account.subscription_id = subscription.id
      account.save

      return true
    rescue
      return false
    end
  end

  def update_subscription(quantity)
    begin
      account = self
      current_user = account.user

      Stripe.api_key = SECRET_KEY

      customer = Stripe::Customer.retrieve(account.customer_id)

      subscription = customer.subscriptions.retrieve(account.subscription_id)
      subscription.quantity = quantity
      subscription.save

      return true
    rescue
      return false
    end
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  before_filter :check_user
  skip_before_filter :check_account

  def index
    @account = current_user.account
  end

  def process_payment
    begin
      account = current_user.account || current_user.create_account(plan: "domain")
      if account.create_customer(params[:stripeToken])
        redirect_to domains_path
      else
        render :payment
      end
    rescue => e
      puts e
      account.destroy if account
      render :payment
    end
  end

  def upgrade
    @account = current_user.account
  end

  def process_upgrade
    account = current_user.account
    if account.update_attributes(account_params) && account.process_upgrade
      redirect_to domains_path
    else
      render :upgrade
    end
  end

  private

    def check_user
      unless current_user
        redirect_to root_path
        return
      end
    end

    def account_params
      params.require(:account).permit(:id, :plan)
    end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/index.html.haml
%h6
  Acount

%hr

%p
  = link_to "Reset password", edit_user_password_path

%p
  = link_to "Update Details", "#"

%p
  = link_to "Close account", "#"

app/views/accounts/payment.html.haml
%h6
  Account - Add payment

%hr

.row
  .col-md-6

    = form_for(:payment, url: process_payment_path, html: {id: "payment-form", class: "form-horizontal"}) do |f|
      %div{class: "alert alert-danger", style: 'display:none;'}
        %button.close.fui-cross{"data-dismiss" => "alert", :type => "button"}
        %span.payment-errors

      .form-group
        = f.label :name, "Card Number", class: " col-md-4 control-label"
        .col-md-8
          %input{"data-stripe" => "number", :size => "20", :type => "text", class: "form-control", placeholder: "1234 1234 1234 1234"}

      .form-group
        %label{class: "col-md-4 control-label"}
          CVC
        .col-md-8
          %input{"data-stripe" => "cvc", :size => "4", :type => "text", class: "form-control", placeholder: "123", min: 000, max: 999}

      .form-group
        %label{class: "col-md-4 control-label"}
          Expiration (MM/YYYY)
        .col-md-8
          %input{"data-stripe" => "exp-month", :size => "2", :type => "text", class: "form-control expiry", placeholder: Time.now.strftime('%m')}
          %span.separator
            \/
          %input{"data-stripe" => "exp-year", :size => "4", :type => "text", class: "form-control expiry", placeholder: Time.now.strftime('%Y')}

      .form-group
        .col-md-offset-4.col-md-8
          %button.btn.btn-primary{:type => "submit"}
            Submit

  .col-md-6
    %p
      Your credit card details are submitted to Stripe to verify you are a real person.
    %p
      You will not be charged until the end of your 30 day trial.
      %br
      All credit card details are processed via Stripe.
    %p
      = image_tag("powered-by-stripe.png")


:javascript
  // This identifies your website in the createToken call below
  Stripe.setPublishableKey("#{PUBLIC_KEY}");

  var stripeResponseHandler = function(status, response) {
    var $form = $('#payment-form');

    if (response.error) {
      // Show the errors on the form
      $form.find('.payment-errors').text(response.error.message);
      $form.find('button').prop('disabled', false);
      $form.find('.alert').show();
    } else {
      // token contains id, last4, and card type
      var token = response.id;
      // Insert the token into the form so it gets submitted to the server
      $form.append($('<input type="hidden" name="stripeToken" />').val(token));
      // and re-submit
      $form.get(0).submit();
    }
  };

  jQuery(function($) {
    $('#payment-form').submit(function(e) {
      var $form = $(this);

      // Disable the submit button to prevent repeated clicks
      $form.find('button').prop('disabled', true);

      Stripe.card.createToken($form, stripeResponseHandler);

      // Prevent the form from submitting with the default action
      return false;
    });
  });

app/views/accounts/upgrade.html.haml
%h1
  Accounts#upgrade
%p
  Find me in app/views/accounts/upgrade.html.haml

%p
  Please upgrade your account
  %br
  All credit card details are processed via Stripe.

= form_for(@account, url: upgrade_path, html: {class: ""}) do |f|

  %fieldset
    %p
      = f.radio_button :plan, "basic2015", disabled: @account.basic?
      = f.label :plan_basic, "basic"
      \$5 mth - 5 Domains
    %p
      = f.radio_button :plan, "plus2015", disabled: @account.plus?
      = f.label :plan_plus, "plus"
      \$25 mth - 25 Domains
    %p
      = f.radio_button :plan, "unlimited2015", disabled: @account.unlimited?
      = f.label :plan_unlimited, "unlimited"
      \$100 mth - Unlmited Domains

  %button
    Create